var ur = window.location.href
var availableTags=[]
//this lines are executed at the beginning, so if the URL is "dirty" with same parameters these lines clean it and
//made the url in the form https://name.something?player=

ur = ur.split("?")

console.log(ur[0])

url = ur[0]+"?player="
url_year="&year=2014"
function is_validname(name)
{
	return(total_tags.indexOf(name)!=-1)
		
}


set_tags(2014)

function setURL(name)
{
	
		if(is_validname(name))
		{	
			console.log("NOME VALIDO")
			name_url = 	name.replace(" ","_")
			my_url = url+name_url+"&year="+current_year
			console.log(url)
			console.log(my_url)
			window.history.pushState({path:my_url},'',my_url);
		}
		else
		alert("Name/URL invalid");
}


function p(x)
{
	console.log(x)
}


avaliableTags=["Giuliano Cornacchia"]


$( function() {
		
		$( "#tags" ).autocomplete({
			source: availableTags,
			select: function (event,ui){	
			setURL(ui.item.label)	
			update()
			},
			focus: function(event,ui){ if(graph_active)	highlight(ui.item.label)},
			close: function(event,ui){ if(graph_active) highlight("")},
			response: function (event,ui){
				console.log(ui.content)
				console.log("AGG GRAPH")
				if(graph_active)
				build_graph(most_similar_player,ui.content)
				}
			
		});
	} );
	
	
function set_tags(year)
{
	if(year!=undefined)
	console.log("set to "+year)
	
	
	if(year==2014)
	{
		availableTags = [
	   'Mike Scott', 'Al Horford', 'Mike Muscala', 'Kent Bazemore',
       'Paul Millsap', 'Thabo Sefolosha', 'Pero Antic', 'Dennis Schroder',
       'Jeff Teague', 'DeMarre Carroll', 'Shelvin Mack', 'Kyle Korver',
       'John Jenkins', 'Austin Daye', 'Elton Brand', 'Adreian Payne',
       'Gerald Henderson', 'Bismack Biyombo', 'Cody Zeller',
       'Michael KiddGilchrist', 'Lance Stephenson', 'Noah Vonleh',
       'Kemba Walker', 'Gary Neal', 'Mo Williams', 'PJ Hairston',
       'Marvin Williams', 'Jeff Taylor', 'Jason Maxiell', 'Brian Roberts',
       'Al Jefferson', 'Jannero Pargo', 'Troy Daniels', 'Jeff Green',
       'James Young', 'Marcus Smart', 'Avery Bradley', 'Gerald Wallace',
       'Brandon Bass', 'Dwight Powell', 'Kelly Olynyk', 'Jonas Jerebko',
       'Tyler Zeller', 'Jae Crowder', 'Evan Turner', 'Phil Pressey',
       'Rajon Rondo', 'Jared Sullinger', 'Tayshaun Prince', 'Gigi Datome',
       'Marcus Thornton', 'Isaiah Thomas', 'Jameer Nelson',
       'Brandan Wright', 'Shavlik Randolph', 'Mason Plumlee',
       'Cory Jefferson', 'Brook Lopez', 'Jerome Jordan', 'Kevin Garnett',
       'Markel Brown', 'Deron Williams', 'Mirza Teletovic', 'Jarrett Jack',
       'Joe Johnson', 'Bojan Bogdanovic', 'Thaddeus Young',
       'Alan Anderson', 'Darius Morris', 'Brandon Davies',
       'Sergey Karasev', 'Earl Clark', 'Jorge Gutierrez',
       'Andrei Kirilenko', 'Nikola Mirotic', 'Pau Gasol', 'Jimmy Butler',
       'Taj Gibson', 'Nazr Mohammed', 'ETwaun Moore', 'Joakim Noah',
       'Derrick Rose', 'Aaron Brooks', 'Tony Snell', 'Doug McDermott',
       'Kirk Hinrich', 'Mike Dunleavy', 'Cameron Bairstow', 'JaVale McGee',
       'Alonzo Gee', 'Timofey Mozgov', 'Kenneth Faried', 'Will Barton',
       'JJ Hickson', 'Wilson Chandler', 'Joffrey Lauvergne',
       'Arron Afflalo', 'Darrell Arthur', 'Ty Lawson', 'Jusuf Nurkic',
       'Danilo Gallinari', 'Gary Harris', 'Erick Green', 'Randy Foye',
       'Nate Robinson', 'Ian Clark', 'Jamaal Franklin', 'Tyson Chandler',
       'AlFarouq Aminu', 'Charlie Villanueva', 'Amare Stoudemire',
       'Richard Jefferson', 'Bernard James', 'Dirk Nowitzki',
       'Jose Juan Barea', 'Devin Harris', 'Chandler Parsons',
       'Monta Ellis', 'Raymond Felton', 'Ricky Ledo', 'Greg Smith',
       'Andrew Bogut', 'Festus Ezeli', 'Shaun Livingston',
       'Andre Iguodala', 'Justin Holiday', 'Harrison Barnes',
       'Klay Thompson', 'Marreese Speights', 'David Lee', 'Draymond Green',
       'Stephen Curry', 'James Michael McAdoo', 'Leandro Barbosa',
       'Brandon Rush', 'Ognjen Kuzmic', 'Tristan Thompson',
       'Iman Shumpert', 'Kevin Love', 'JR Smith', 'Shawn Marion',
       'LeBron James', 'Kendrick Perkins', 'Kyrie Irving', 'James Jones',
       'Matthew Dellavedova', 'Dion Waiters', 'Joe Harris', 'Will Cherry',
       'AJ Price', 'Anderson Varejao', 'Brendan Haywood', 'Lou Amundson',
       'Mike Miller', 'Alex Kirk', 'Wesley Johnson', 'Ed Davis',
       'Jordan Clarkson', 'Tarik Black', 'Jabari Brown', 'Ryan Kelly',
       'Wayne Ellington', 'Ronnie Price', 'Nick Young', 'Jordan Hill',
       'Vander Blue', 'Kobe Bryant', 'Jeremy Lin', 'Carlos Boozer',
       'Robert Sacre', 'Dwight Buycks', 'Julius Randle', 'Xavier Henry',
       'Gorgui Dieng', 'Zach LaVine', 'Andrew Wiggins', 'Chase Budinger',
       'Justin Hamilton', 'Shabazz Muhammad', 'Kevin Martin',
       'Corey Brewer', 'Lorenzo Brown', 'Anthony Bennett',
       'Sean Kilpatrick', 'Nikola Pekovic', 'Ricky Rubio', 'Jeff Adrien',
       'Glenn Robinson', 'Robbie Hummel', 'Arinze Onuaku',
       'Miroslav Raduljica', 'Carmelo Anthony', 'Samuel Dalembert',
       'Quincy Acy', 'Tim Hardaway Jr', 'Cleanthony Early', 'Jason Smith',
       'Travis Wear', 'Shane Larkin', 'Andrea Bargnani',
       'Langston Galloway', 'Cole Aldrich', 'Alexey Shved', 'Lance Thomas',
       'Pablo Prigioni', 'Jose Calderon', 'Andre Drummond', 'Joel Anthony',
       'Kentavious CaldwellPope', 'Greg Monroe', 'Josh Smith',
       'Shawne Williams', 'Reggie Jackson', 'DJ Augustin',
       'Brandon Jennings', 'Jodie Meeks', 'Caron Butler',
       'Spencer Dinwiddie', 'Kyle Singler', 'Anthony Tolliver',
       'Cartier Martin', 'John Lucas III', 'Quincy Miller',
       'Andre Roberson', 'Steven Adams', 'Kevin Durant', 'Serge Ibaka',
       'Russell Westbrook', 'Perry Jones', 'Jeremy Lamb', 'Anthony Morrow',
       'Nick Collison', 'Mitch McGary', 'Sebastian Telfair', 'Ish Smith',
       'Enes Kanter', 'Grant Jerrett', 'Steve Novak', 'Nerlens Noel',
       'JaKarr Sampson', 'KJ McDaniels', 'Malcolm Thomas',
       'Michael CarterWilliams', 'Thomas Robinson', 'Robert Covington',
       'Jerami Grant', 'Hollis Thompson', 'Henry Sims', 'Isaiah Canaan',
       'Jason Richardson', 'Luc Mbah a Moute', 'Tony Wroten',
       'Tim Frazier', 'Malcolm Lee', 'Furkan Aldemir', 'Chris Johnson',
       'Larry Drew', 'Drew Gordon', 'Dewayne Dedmon', 'Victor Oladipo',
       'Aaron Gordon', 'Maurice Harkless', 'Nikola Vucevic',
       'Tobias Harris', 'Evan Fournier', 'Willie Green', 'Elfrid Payton',
       'Channing Frye', 'Kyle OQuinn', 'Devyn Marble', 'Ben Gordon',
       'Luke Ridnour', 'Andrew Nicholson', 'Robin Lopez', 'Nicolas Batum',
       'LaMarcus Aldridge', 'Damian Lillard', 'Allen Crabbe',
       'Meyers Leonard', 'Victor Claver', 'Chris Kaman', 'Wesley Matthews',
       'Dorell Wright', 'Joel Freeland', 'CJ McCollum', 'Steve Blake',
       'Markieff Morris', 'Miles Plumlee', 'Marcus Morris', 'Alex Len',
       'Archie Goodwin', 'Gerald Green', 'Eric Bledsoe', 'PJ Tucker',
       'Goran Dragic', 'TJ Warren', 'Brandon Knight', 'Zoran Dragic',
       'Tyler Ennis', 'Reggie Bullock', 'Earl Barron', 'Jerel McNeal',
       'Seth Curry', 'Chris Andersen', 'Hassan Whiteside', 'Tyler Johnson',
       'James Ennis', 'Chris Bosh', 'Josh McRoberts', 'Udonis Haslem',
       'Michael Beasley', 'Dwyane Wade', 'Mario Chalmers', 'Henry Walker',
       'Shannon Brown', 'Luol Deng', 'Shabazz Napier', 'Norris Cole',
       'Danny Granger', 'Andre Dawkins', 'Ben McLemore',
       'Derrick Williams', 'Rudy Gay', 'DeMarcus Cousins', 'Ryan Hollins',
       'Ray McCallum', 'Jason Thompson', 'Omri Casspi', 'Ramon Sessions',
       'Reggie Evans', 'Darren Collison', 'Nik Stauskas', 'Andre Miller',
       'Carl Landry', 'David Stockton', 'Sim Bhullar', 'Eric Moreland',
       'David Wear', 'Terrence Ross', 'Patrick Patterson', 'Amir Johnson',
       'James Johnson', 'Lucas Nogueira', 'Jonas Valanciunas',
       'DeMar DeRozan', 'Bruno Caboclo', 'Landry Fields', 'Greg Stiemsma',
       'Tyler Hansbrough', 'Lou Williams', 'Kyle Lowry', 'Greivis Vasquez',
       'Louis Williams', 'Charles Hayes', 'Otto Porter', 'Marcin Gortat',
       'John Wall', 'Martell Webster', 'Rasual Butler', 'Bradley Beal',
       'Kevin Seraphin', 'Kris Humphries', 'Garrett Temple', 'Nene',
       'Paul Pierce', 'Toure Murry', 'Drew Gooden', 'Glen Rice Jr',
       'DeJuan Blair', 'Will Bynum', 'John Henson',
       'Giannis Antetokounmpo', 'Jerryd Bayless', 'Kenyon Martin',
       'Larry Sanders', 'Jabari Parker', 'Ersan Ilyasova',
       'Khris Middleton', 'Nate Wolters', 'OJ Mayo', 'Jared Dudley',
       'Zaza Pachulia', 'Johnny OBryant', 'Kendall Marshall',
       'Rudy Gobert', 'Jeremy Evans', 'Gordon Hayward', 'Derrick Favors',
       'Trevor Booker', 'Bryce Cotton', 'Trey Burke', 'Alec Burks',
       'Joe Ingles', 'Elijah Millsap', 'Dante Exum', 'Rodney Hood',
       'Patrick Christopher', 'Jack Cooley', 'Elliot Williams',
       'Anthony Davis', 'Austin Rivers', 'Alexis Ajinca',
       'Dante Cunningham', 'Jeff Withey', 'Omer Asik', 'Tyreke Evans',
       'Jrue Holiday', 'Ryan Anderson', 'Eric Gordon', 'Luke Babbitt',
       'Toney Douglas', 'Quincy Pondexter', 'John Salmons',
       'Jimmer Fredette', 'Gal Mekel', 'Darius Miller', 'Russ Smith',
       'Ian Mahinmi', 'CJ Miles', 'Solomon Hill', 'Rodney Stuckey',
       'CJ Watson', 'Luis Scola', 'Donald Sloan', 'George Hill',
       'Chris Copeland', 'Damjan Rudez', 'David West', 'Roy Hibbert',
       'Lavoy Allen', 'Paul George', 'Shayne Whittington', 'Blake Griffin',
       'DeAndre Jordan', 'Matt Barnes', 'Spencer Hawes', 'Glen Davis',
       'Jamal Crawford', 'Chris Paul', 'JJ Redick', 'Chris DouglasRoberts',
       'Jordan Farmar', 'Hedo Turkoglu', 'Jared Cunningham',
       'Lester Hudson', 'CJ Wilcox', 'Dahntay Jones', 'Jordan Hamilton',
       'Ekpe Udoh', 'Aron Baynes', 'Kawhi Leonard', 'Jeff Ayres',
       'Tim Duncan', 'Marco Belinelli', 'Boris Diaw', 'Danny Green',
       'Manu Ginobili', 'Tony Parker', 'Cory Joseph', 'Tiago Splitter',
       'Reggie Williams', 'Kyle Anderson', 'Matt Bonner', 'Patty Mills',
       'JaMychal Green', 'Dwight Howard', 'Joey Dorsey', 'Clint Capela',
       'Terrence Jones', 'James Harden', 'Kostas Papanikolaou',
       'Nick Johnson', 'Donatas Motiejunas', 'Patrick Beverley',
       'Trevor Ariza', 'Jason Terry', 'Francisco Garcia', 'Kosta Koufos',
       'Jon Leuer', 'Marc Gasol', 'Courtney Lee', 'Tony Allen',
       'Vince Carter', 'Mike Conley', 'Nick Calathes', 'Beno Udrih',
       'Zach Randolph', 'Jordan Adams', 'Jarnell Stokes', 'Kalin Lucas',
       'Tyrus Thomas'
		]
	}
	else if(year==2017)
		availableTags = ["LeBron James",
"Anthony Davis",
"Russell Westbrook",
"Giannis Antetokounmpo",
"LaMarcus Aldridge",
"Bradley Beal",
"CJ McCollum",
"KarlAnthony Towns",
"James Harden",
"DeMar DeRozan",
"Victor Oladipo",
"Damian Lillard",
"Kevin Durant",
"Donovan Mitchell",
"Jrue Holiday",
"Andrew Wiggins",
"Khris Middleton",
"Kemba Walker",
"Paul George",
"Lou Williams",
"Klay Thompson",
"TJ Warren",
"Harrison Barnes",
"Tobias Harris",
"Kyrie Irving",
"Ben Simmons",
"Dennis Schroder",
"Julius Randle",
"Andre Drummond",
"Goran Dragic",
"Devin Booker",
"Dwight Howard",
"Jusuf Nurkic",
"Joel Embiid",
"Carmelo Anthony",
"Nikola Jokic",
"Steven Adams",
"Eric Bledsoe",
"Jamal Murray",
"Otto Porter Jr",
"Jimmy Butler",
"Will Barton",
"Kyle Kuzma",
"Marc Gasol",
"Enes Kanter",
"Jordan Clarkson",
"Dennis Smith Jr",
"Blake Griffin",
"Taj Gibson",
"ETwaun Moore",
"Thaddeus Young",
"Kristaps Porzingis",
"Bojan Bogdanovic",
"Stephen Curry",
"DeMarcus Cousins",
"Clint Capela",
"Josh Jackson",
"Buddy Hield",
"Kyle Lowry",
"Gary Harris",
"Taurean Prince",
"Jayson Tatum",
"Derrick Favors",
"Jaylen Brown",
"Josh Richardson",
"JJ Redick",
"Michael Beasley",
"Eric Gordon",
"Ish Smith",
"Evan Fournier",
"Willie CauleyStein",
"Dario Saric",
"Al Horford",
"Jeremy Lamb",
"Nikola Vucevic",
"Serge Ibaka",
"Jonas Valanciunas",
"Aaron Gordon",
"Lauri Markkanen",
"Tyreke Evans",
"Courtney Lee",
"Brandon Ingram",
"DeAndre Jordan",
"Bobby Portis",
"Jeff Teague",
"Dirk Nowitzki",
"Zach Randolph",
"Tim Hardaway Jr",
"Kevin Love",
"Jonathon Simmons",
"Brook Lopez",
"Robert Covington",
"Austin Rivers",
"Rondae HollisJefferson",
"Allen Crabbe",
"Marco Belinelli",
"Bogdan Bogdanovic",
"Domantas Sabonis",
"Ricky Rubio",
"Montrezl Harrell",
"Chris Paul",
"Robin Lopez",
"Hassan Whiteside",
"Elfrid Payton",
"Kelly Oubre Jr",
"Dillon Brooks",
"Joe Ingles",
"Terry Rozier",
"Spencer Dinwiddie",
"Kentavious CaldwellPope",
"Caris LeVert",
"DeMarre Carroll",
"Rodney Hood",
"Yogi Ferrell",
"Markieff Morris",
"DeAaron Fox",
"Darren Collison",
"JJ Barea",
"Joe Harris",
"John Collins",
"Lance Stephenson",
"Wesley Matthews",
"Jamal Crawford",
"Kelly Olynyk",
"Jeff Green",
"Pau Gasol",
"Frank Kaminsky",
"Marcin Gortat",
"Dwyane Wade",
"James Johnson",
"Denzel Valentine",
"John Wall",
"Justin Holiday",
"Nikola Mirotic",
"Tyler Johnson",
"John Henson",
"Myles Turner",
"Patty Mills",
"Kent Bazemore",
"Mario Hezonja",
"Draymond Green",
"Avery Bradley",
"Wayne Ellington",
"Mike Scott",
"Michael KiddGilchrist",
"Ersan Ilyasova",
"Reggie Jackson",
"Jae Crowder",
"Rudy Gobert",
"DAngelo Russell",
"Marcus Morris",
"Dejounte Murray",
"Dwight Powell",
"Wilson Chandler",
"Kris Dunn",
"Evan Turner",
"Malcolm Brogdon",
"Jakob Poeltl",
"Dewayne Dedmon",
"Trey Lyles",
"Nicolas Batum",
"Rudy Gay",
"Reggie Bullock",
"Pascal Siakam",
"Trevor Ariza",
"Cory Joseph",
"Marvin Williams",
"JR Smith",
"Doug McDermott",
"Jerami Grant",
"Troy Daniels",
"George Hill",
"Kyle Anderson",
"Jarrett Allen",
"DJ Augustin",
"Fred VanVleet",
"Larry Nance Jr",
"AlFarouq Aminu",
"Alex Len",
"Greg Monroe",
"Raymond Felton",
"CJ Miles",
"Tyler Ulis",
"Stanley Johnson",
"Danny Green",
"Anthony Tolliver",
"Rajon Rondo",
"Jerian Grant",
"David West",
"Kyle Korver",
"Kyle OQuinn",
"Aron Baynes",
"JaMychal Green",
"Marquese Chriss",
"Jarell Martin",
"Mason Plumlee",
"Shabazz Napier",
"Darius Miller",
"Manu Ginobili",
"Bryn Forbes",
"Ryan Anderson",
"Ian Clark",
"Kosta Koufos",
"Luke Kennard",
"Jarrett Jack",
"Skal Labissiere",
"TJ McConnell",
"Nick Young",
"Emmanuel Mudiay",
"Justise Winslow",
"Dragan Bender",
"David Nwaba",
"Gorgui Dieng",
"Delon Wright",
"Bismack Biyombo",
"Garrett Temple",
"Tomas Satoransky",
"Lonzo Ball",
"Andrew Harrison",
"Paul Millsap",
"Trey Burke",
"Marcus Smart",
"Tony Snell",
"Frank Ntilikina",
"Tyler Zeller",
"Trevor Booker",
"Devin Harris",
"Josh Hart",
"James Ennis III",
"OG Anunoby",
"Alec Burks",
"Shelvin Mack",
"Justin Jackson",
"Pat Connaughton",
"Mario Chalmers",
"Bam Adebayo",
"Ed Davis",
"PJ Tucker",
"Isaiah Taylor",
"Dion Waiters",
"Tony Parker",
"Nemanja Bjelica",
"Maxi Kleber",
"Luc Mbah a Moute",
"Shaun Livingston",
"Gerald Green",
"Wesley Johnson",
"Deyonta Davis",
"Dante Cunningham",
"Jodie Meeks",
"Davis Bertans",
"Jabari Parker",
"Jonas Jerebko",
"Tyus Jones",
"Malik Monk",
"Maurice Harkless",
"Ben McLemore",
"Norman Powell",
"Joe Johnson",
"Amir Johnson",
"Milos Teodosic",
"Mike Muscala",
"Andre Iguodala",
"Zaza Pachulia",
"Marreese Speights",
"Nene",
"Tristan Thompson",
"Frank Mason",
"Richaun Holmes",
"Tyler Dorsey",
"Ian Mahinmi",
"Thon Maker",
"Mike James",
"Cristiano Felicio",
"Quincy Acy",
"Langston Galloway",
"Sam Dekker",
"Daniel Theis",
"Corey Brewer",
"Thabo Sefolosha",
"Tyson Chandler",
"Quinn Cook",
"Royce ONeale",
"JaVale McGee",
"Isaiah Thomas",
"Sean Kilpatrick",
"Jordan Bell",
"Malcolm Delaney",
"Wayne Selden",
"Zach LaVine",
"Channing Frye",
"Danilo Gallinari",
"Jerryd Bayless",
"Tyrone Wallace",
"Omri Casspi",
"Al Jefferson",
"Vince Carter",
"Alex Abrines",
"Zach Collins",
"Kevon Looney",
"Miles Plumlee",
"Lance Thomas",
"Timothe LuwawuCabarrot",
"Patrick Patterson",
"Jameer Nelson",
"Chandler Parsons",
"Patrick McCaw",
"Cheick Diallo",
"Luke Babbitt",
"Jose Calderon",
"Willy Hernangomez",
"Noah Vonleh",
"Salah Mejri",
"Cedi Osman",
"Justin Anderson",
"Treveon Graham",
"Joffrey Lauvergne",
"Ivan Rabb",
"Tyler Ennis",
"Andre Roberson",
"Sindarius Thornwell",
"Derrick Rose",
"Wes Iwundu",
"Shabazz Muhammad",
"CJ Williams",
"Paul Zipser",
"Kenneth Faried",
"Cody Zeller",
"Terrence Ross",
"Joe Young",
"Dwayne Bacon",
"Willie Reed",
"Shane Larkin",
"Boban Marjanovic",
"Cameron Payne",
"Michael CarterWilliams",
"Tim Frazier",
"Terrance Ferguson",
"Kobi Simmons",
"Malik Beasley",
"Jawun Evans",
"Jahlil Okafor",
"Damyean Dotson",
"Sterling Brown",
"Raul Neto",
"Dwight Buycks",
"Tarik Black",
"Tyler Cavanaugh",
"Khem Birch",
"Mike Conley",
"Johnny OBryant III",
"Semi Ojeleye",
"Arron Afflalo",
"Jason Terry",
"Brandan Wright",
"TJ Leaf",
"Danuel House",
"Matthew Dellavedova",
"Ekpe Udoh",
"Torrey Craig",
"Henry Ellenson",
"Damion Lee",
"Eric Moreland",
"Nik Stauskas",
"Ivica Zubac",
"MarShon Brooks",
"DeAndre Bembry",
"Timofey Mozgov",
"Josh Huestis",
"Brandon Paul",
"Lucas Nogueira",
"Patrick Beverley",
"Nerlens Noel",
"Meyers Leonard",
"Isaiah Canaan",
"Abdel Nader",
"Markelle Fultz",
"Shaquille Harrison",
"Jonathan Isaac",
"Kawhi Leonard",
"Dorian FinneySmith",
"Alex Caruso",
"Tony Allen",
"JaKarr Sampson",
"Jared Dudley",
"Luke Kornet",
"Johnathan Motley",
"Myke Henry",
"Dante Exum",
"Jason Smith",
"Kyle Collinsworth",
"Troy Williams",
"Antonio Blakeney",
"DeAndre Liggins",
"Isaiah Whitehead",
"Ante Zizic",
"Ramon Sessions",
"Isaiah Hicks",
"Jamel Artis",
"Glenn Robinson III",
"Rodney Purvis",
"Jamil Wilson",
"Jordan Mickey",
"Malachi Richardson",
"Gary Payton II",
"Jalen Jones",
"Aaron Brooks",
"Emeka Okafor",
"Alec Peters",
"Mirza Teletovic",
"Guerschon Yabusele",
"Rodney McGruder",
"Caleb Swanigan",
"Iman Shumpert",
"Juan Hernangomez",
"Derrick Jones Jr",
"Kay Felder",
"Brandon Jennings",
"Darrell Arthur",
"Rashad Vaughn",
"Marcus GeorgesHunt",
"Aaron Harrison",
"Travis Wear",
"Georgios Papagiannis",
"Ron Baker",
"Chris McCullough",
"Dakari Johnson",
"Briante Weber",
"Ryan Arcidiacono",
"Brice Johnson",
"Jon Leuer",
"Jabari Bird",
"Davon Reed",
"Jake Layman",
"Andrew Bogut",
"Wade Baldwin IV",
"Jonathan Gibson",
"Quincy Pondexter",
"Bobby Brown",
"Lorenzo Brown",
"Andrew White III",
"Josh Magette",
"Derrick White",
"Richard Jefferson",
"John Holland",
"Milton Doyle",
"Josh Gray",
"Solomon Hill",
"Damian Jones",
"Damien Wilkins",
"Alex Poythress",
"Omari Johnson",
"Jack Cooley",
"Omer Asik",
"Nigel Hayes",
"DJ Wilson",
"Antonius Cleveland",
"Furkan Korkmaz",
"Alfonzo McKinnie",
"Thomas Bryant",
"Nick Collison",
"Andre Ingram",
"Adreian Payne",
"Okaro White",
"Alan Williams",
"Kyle Singler",
"Jordan Crawford",
"Larry Drew II",
"Demetrius Jackson",
"Bruno Caboclo",
"Derrick Walton Jr",
"RJ Hunter",
"Zhou Qi",
"Jeff Withey",
"Gian Clavell",
"Julyan Stone",
"Andrew White",
"James Webb III",
"Kadeem Allen",
"James Young",
"Jeremy Lin",
"Daniel Hamilton",
"Jaylen Morris",
"Darrun Hilliard",
"Joakim Noah",
"Walter Lemon Jr",
"Ike Anigbogu",
"Monte Morris",
"Cole Aldrich",
"Xavier RathanMayes",
"Mangok Mathiang",
"Malcolm Miller",
"Marcus Paige",
"Marquis Teague",
"Aaron Jackson",
"Joel Bolomboy",
"Vincent Hunter",
"Tony Bradley",
"Juancho Hernangomez",
"Udonis Haslem"]




		
		$( "#tags" ).autocomplete({
			source: availableTags,
			select: function (event,ui){	
			setURL(ui.item.label)	
			update()
			},
			focus: function(event,ui){ if(graph_active)	highlight(ui.item.label)},
			close: function(event,ui){ if(graph_active) highlight("")},
			response: function (event,ui){
				console.log(ui.content)
				console.log("AGG GRAPH")
				if(graph_active)
					build_graph(most_similar_player,ui.content)
				}
			
		});
	
	
}	

var total_tags=[
	   'Mike Scott', 'Al Horford', 'Mike Muscala', 'Kent Bazemore',
       'Paul Millsap', 'Thabo Sefolosha', 'Pero Antic', 'Dennis Schroder',
       'Jeff Teague', 'DeMarre Carroll', 'Shelvin Mack', 'Kyle Korver',
       'John Jenkins', 'Austin Daye', 'Elton Brand', 'Adreian Payne',
       'Gerald Henderson', 'Bismack Biyombo', 'Cody Zeller',
       'Michael KiddGilchrist', 'Lance Stephenson', 'Noah Vonleh',
       'Kemba Walker', 'Gary Neal', 'Mo Williams', 'PJ Hairston',
       'Marvin Williams', 'Jeff Taylor', 'Jason Maxiell', 'Brian Roberts',
       'Al Jefferson', 'Jannero Pargo', 'Troy Daniels', 'Jeff Green',
       'James Young', 'Marcus Smart', 'Avery Bradley', 'Gerald Wallace',
       'Brandon Bass', 'Dwight Powell', 'Kelly Olynyk', 'Jonas Jerebko',
       'Tyler Zeller', 'Jae Crowder', 'Evan Turner', 'Phil Pressey',
       'Rajon Rondo', 'Jared Sullinger', 'Tayshaun Prince', 'Gigi Datome',
       'Marcus Thornton', 'Isaiah Thomas', 'Jameer Nelson',
       'Brandan Wright', 'Shavlik Randolph', 'Mason Plumlee',
       'Cory Jefferson', 'Brook Lopez', 'Jerome Jordan', 'Kevin Garnett',
       'Markel Brown', 'Deron Williams', 'Mirza Teletovic', 'Jarrett Jack',
       'Joe Johnson', 'Bojan Bogdanovic', 'Thaddeus Young',
       'Alan Anderson', 'Darius Morris', 'Brandon Davies',
       'Sergey Karasev', 'Earl Clark', 'Jorge Gutierrez',
       'Andrei Kirilenko', 'Nikola Mirotic', 'Pau Gasol', 'Jimmy Butler',
       'Taj Gibson', 'Nazr Mohammed', 'ETwaun Moore', 'Joakim Noah',
       'Derrick Rose', 'Aaron Brooks', 'Tony Snell', 'Doug McDermott',
       'Kirk Hinrich', 'Mike Dunleavy', 'Cameron Bairstow', 'JaVale McGee',
       'Alonzo Gee', 'Timofey Mozgov', 'Kenneth Faried', 'Will Barton',
       'JJ Hickson', 'Wilson Chandler', 'Joffrey Lauvergne',
       'Arron Afflalo', 'Darrell Arthur', 'Ty Lawson', 'Jusuf Nurkic',
       'Danilo Gallinari', 'Gary Harris', 'Erick Green', 'Randy Foye',
       'Nate Robinson', 'Ian Clark', 'Jamaal Franklin', 'Tyson Chandler',
       'AlFarouq Aminu', 'Charlie Villanueva', 'Amare Stoudemire',
       'Richard Jefferson', 'Bernard James', 'Dirk Nowitzki',
       'Jose Juan Barea', 'Devin Harris', 'Chandler Parsons',
       'Monta Ellis', 'Raymond Felton', 'Ricky Ledo', 'Greg Smith',
       'Andrew Bogut', 'Festus Ezeli', 'Shaun Livingston',
       'Andre Iguodala', 'Justin Holiday', 'Harrison Barnes',
       'Klay Thompson', 'Marreese Speights', 'David Lee', 'Draymond Green',
       'Stephen Curry', 'James Michael McAdoo', 'Leandro Barbosa',
       'Brandon Rush', 'Ognjen Kuzmic', 'Tristan Thompson',
       'Iman Shumpert', 'Kevin Love', 'JR Smith', 'Shawn Marion',
       'LeBron James', 'Kendrick Perkins', 'Kyrie Irving', 'James Jones',
       'Matthew Dellavedova', 'Dion Waiters', 'Joe Harris', 'Will Cherry',
       'AJ Price', 'Anderson Varejao', 'Brendan Haywood', 'Lou Amundson',
       'Mike Miller', 'Alex Kirk', 'Wesley Johnson', 'Ed Davis',
       'Jordan Clarkson', 'Tarik Black', 'Jabari Brown', 'Ryan Kelly',
       'Wayne Ellington', 'Ronnie Price', 'Nick Young', 'Jordan Hill',
       'Vander Blue', 'Kobe Bryant', 'Jeremy Lin', 'Carlos Boozer',
       'Robert Sacre', 'Dwight Buycks', 'Julius Randle', 'Xavier Henry',
       'Gorgui Dieng', 'Zach LaVine', 'Andrew Wiggins', 'Chase Budinger',
       'Justin Hamilton', 'Shabazz Muhammad', 'Kevin Martin',
       'Corey Brewer', 'Lorenzo Brown', 'Anthony Bennett',
       'Sean Kilpatrick', 'Nikola Pekovic', 'Ricky Rubio', 'Jeff Adrien',
       'Glenn Robinson', 'Robbie Hummel', 'Arinze Onuaku',
       'Miroslav Raduljica', 'Carmelo Anthony', 'Samuel Dalembert',
       'Quincy Acy', 'Tim Hardaway Jr', 'Cleanthony Early', 'Jason Smith',
       'Travis Wear', 'Shane Larkin', 'Andrea Bargnani',
       'Langston Galloway', 'Cole Aldrich', 'Alexey Shved', 'Lance Thomas',
       'Pablo Prigioni', 'Jose Calderon', 'Andre Drummond', 'Joel Anthony',
       'Kentavious CaldwellPope', 'Greg Monroe', 'Josh Smith',
       'Shawne Williams', 'Reggie Jackson', 'DJ Augustin',
       'Brandon Jennings', 'Jodie Meeks', 'Caron Butler',
       'Spencer Dinwiddie', 'Kyle Singler', 'Anthony Tolliver',
       'Cartier Martin', 'John Lucas III', 'Quincy Miller',
       'Andre Roberson', 'Steven Adams', 'Kevin Durant', 'Serge Ibaka',
       'Russell Westbrook', 'Perry Jones', 'Jeremy Lamb', 'Anthony Morrow',
       'Nick Collison', 'Mitch McGary', 'Sebastian Telfair', 'Ish Smith',
       'Enes Kanter', 'Grant Jerrett', 'Steve Novak', 'Nerlens Noel',
       'JaKarr Sampson', 'KJ McDaniels', 'Malcolm Thomas',
       'Michael CarterWilliams', 'Thomas Robinson', 'Robert Covington',
       'Jerami Grant', 'Hollis Thompson', 'Henry Sims', 'Isaiah Canaan',
       'Jason Richardson', 'Luc Mbah a Moute', 'Tony Wroten',
       'Tim Frazier', 'Malcolm Lee', 'Furkan Aldemir', 'Chris Johnson',
       'Larry Drew', 'Drew Gordon', 'Dewayne Dedmon', 'Victor Oladipo',
       'Aaron Gordon', 'Maurice Harkless', 'Nikola Vucevic',
       'Tobias Harris', 'Evan Fournier', 'Willie Green', 'Elfrid Payton',
       'Channing Frye', 'Kyle OQuinn', 'Devyn Marble', 'Ben Gordon',
       'Luke Ridnour', 'Andrew Nicholson', 'Robin Lopez', 'Nicolas Batum',
       'LaMarcus Aldridge', 'Damian Lillard', 'Allen Crabbe',
       'Meyers Leonard', 'Victor Claver', 'Chris Kaman', 'Wesley Matthews',
       'Dorell Wright', 'Joel Freeland', 'CJ McCollum', 'Steve Blake',
       'Markieff Morris', 'Miles Plumlee', 'Marcus Morris', 'Alex Len',
       'Archie Goodwin', 'Gerald Green', 'Eric Bledsoe', 'PJ Tucker',
       'Goran Dragic', 'TJ Warren', 'Brandon Knight', 'Zoran Dragic',
       'Tyler Ennis', 'Reggie Bullock', 'Earl Barron', 'Jerel McNeal',
       'Seth Curry', 'Chris Andersen', 'Hassan Whiteside', 'Tyler Johnson',
       'James Ennis', 'Chris Bosh', 'Josh McRoberts', 'Udonis Haslem',
       'Michael Beasley', 'Dwyane Wade', 'Mario Chalmers', 'Henry Walker',
       'Shannon Brown', 'Luol Deng', 'Shabazz Napier', 'Norris Cole',
       'Danny Granger', 'Andre Dawkins', 'Ben McLemore',
       'Derrick Williams', 'Rudy Gay', 'DeMarcus Cousins', 'Ryan Hollins',
       'Ray McCallum', 'Jason Thompson', 'Omri Casspi', 'Ramon Sessions',
       'Reggie Evans', 'Darren Collison', 'Nik Stauskas', 'Andre Miller',
       'Carl Landry', 'David Stockton', 'Sim Bhullar', 'Eric Moreland',
       'David Wear', 'Terrence Ross', 'Patrick Patterson', 'Amir Johnson',
       'James Johnson', 'Lucas Nogueira', 'Jonas Valanciunas',
       'DeMar DeRozan', 'Bruno Caboclo', 'Landry Fields', 'Greg Stiemsma',
       'Tyler Hansbrough', 'Lou Williams', 'Kyle Lowry', 'Greivis Vasquez',
       'Louis Williams', 'Charles Hayes', 'Otto Porter', 'Marcin Gortat',
       'John Wall', 'Martell Webster', 'Rasual Butler', 'Bradley Beal',
       'Kevin Seraphin', 'Kris Humphries', 'Garrett Temple', 'Nene',
       'Paul Pierce', 'Toure Murry', 'Drew Gooden', 'Glen Rice Jr',
       'DeJuan Blair', 'Will Bynum', 'John Henson',
       'Giannis Antetokounmpo', 'Jerryd Bayless', 'Kenyon Martin',
       'Larry Sanders', 'Jabari Parker', 'Ersan Ilyasova',
       'Khris Middleton', 'Nate Wolters', 'OJ Mayo', 'Jared Dudley',
       'Zaza Pachulia', 'Johnny OBryant', 'Kendall Marshall',
       'Rudy Gobert', 'Jeremy Evans', 'Gordon Hayward', 'Derrick Favors',
       'Trevor Booker', 'Bryce Cotton', 'Trey Burke', 'Alec Burks',
       'Joe Ingles', 'Elijah Millsap', 'Dante Exum', 'Rodney Hood',
       'Patrick Christopher', 'Jack Cooley', 'Elliot Williams',
       'Anthony Davis', 'Austin Rivers', 'Alexis Ajinca',
       'Dante Cunningham', 'Jeff Withey', 'Omer Asik', 'Tyreke Evans',
       'Jrue Holiday', 'Ryan Anderson', 'Eric Gordon', 'Luke Babbitt',
       'Toney Douglas', 'Quincy Pondexter', 'John Salmons',
       'Jimmer Fredette', 'Gal Mekel', 'Darius Miller', 'Russ Smith',
       'Ian Mahinmi', 'CJ Miles', 'Solomon Hill', 'Rodney Stuckey',
       'CJ Watson', 'Luis Scola', 'Donald Sloan', 'George Hill',
       'Chris Copeland', 'Damjan Rudez', 'David West', 'Roy Hibbert',
       'Lavoy Allen', 'Paul George', 'Shayne Whittington', 'Blake Griffin',
       'DeAndre Jordan', 'Matt Barnes', 'Spencer Hawes', 'Glen Davis',
       'Jamal Crawford', 'Chris Paul', 'JJ Redick', 'Chris DouglasRoberts',
       'Jordan Farmar', 'Hedo Turkoglu', 'Jared Cunningham',
       'Lester Hudson', 'CJ Wilcox', 'Dahntay Jones', 'Jordan Hamilton',
       'Ekpe Udoh', 'Aron Baynes', 'Kawhi Leonard', 'Jeff Ayres',
       'Tim Duncan', 'Marco Belinelli', 'Boris Diaw', 'Danny Green',
       'Manu Ginobili', 'Tony Parker', 'Cory Joseph', 'Tiago Splitter',
       'Reggie Williams', 'Kyle Anderson', 'Matt Bonner', 'Patty Mills',
       'JaMychal Green', 'Dwight Howard', 'Joey Dorsey', 'Clint Capela',
       'Terrence Jones', 'James Harden', 'Kostas Papanikolaou',
       'Nick Johnson', 'Donatas Motiejunas', 'Patrick Beverley',
       'Trevor Ariza', 'Jason Terry', 'Francisco Garcia', 'Kosta Koufos',
       'Jon Leuer', 'Marc Gasol', 'Courtney Lee', 'Tony Allen',
       'Vince Carter', 'Mike Conley', 'Nick Calathes', 'Beno Udrih',
       'Zach Randolph', 'Jordan Adams', 'Jarnell Stokes', 'Kalin Lucas',
       'Tyrus Thomas',"LeBron James",
"Anthony Davis",
"Russell Westbrook",
"Giannis Antetokounmpo",
"LaMarcus Aldridge",
"Bradley Beal",
"CJ McCollum",
"KarlAnthony Towns",
"James Harden",
"DeMar DeRozan",
"Victor Oladipo",
"Damian Lillard",
"Kevin Durant",
"Donovan Mitchell",
"Jrue Holiday",
"Andrew Wiggins",
"Khris Middleton",
"Kemba Walker",
"Paul George",
"Lou Williams",
"Klay Thompson",
"TJ Warren",
"Harrison Barnes",
"Tobias Harris",
"Kyrie Irving",
"Ben Simmons",
"Dennis Schroder",
"Julius Randle",
"Andre Drummond",
"Goran Dragic",
"Devin Booker",
"Dwight Howard",
"Jusuf Nurkic",
"Joel Embiid",
"Carmelo Anthony",
"Nikola Jokic",
"Steven Adams",
"Eric Bledsoe",
"Jamal Murray",
"Otto Porter Jr",
"Jimmy Butler",
"Will Barton",
"Kyle Kuzma",
"Marc Gasol",
"Enes Kanter",
"Jordan Clarkson",
"Dennis Smith Jr",
"Blake Griffin",
"Taj Gibson",
"ETwaun Moore",
"Thaddeus Young",
"Kristaps Porzingis",
"Bojan Bogdanovic",
"Stephen Curry",
"DeMarcus Cousins",
"Clint Capela",
"Josh Jackson",
"Buddy Hield",
"Kyle Lowry",
"Gary Harris",
"Taurean Prince",
"Jayson Tatum",
"Derrick Favors",
"Jaylen Brown",
"Josh Richardson",
"JJ Redick",
"Michael Beasley",
"Eric Gordon",
"Ish Smith",
"Evan Fournier",
"Willie CauleyStein",
"Dario Saric",
"Al Horford",
"Jeremy Lamb",
"Nikola Vucevic",
"Serge Ibaka",
"Jonas Valanciunas",
"Aaron Gordon",
"Lauri Markkanen",
"Tyreke Evans",
"Courtney Lee",
"Brandon Ingram",
"DeAndre Jordan",
"Bobby Portis",
"Jeff Teague",
"Dirk Nowitzki",
"Zach Randolph",
"Tim Hardaway Jr",
"Kevin Love",
"Jonathon Simmons",
"Brook Lopez",
"Robert Covington",
"Austin Rivers",
"Rondae HollisJefferson",
"Allen Crabbe",
"Marco Belinelli",
"Bogdan Bogdanovic",
"Domantas Sabonis",
"Ricky Rubio",
"Montrezl Harrell",
"Chris Paul",
"Robin Lopez",
"Hassan Whiteside",
"Elfrid Payton",
"Kelly Oubre Jr",
"Dillon Brooks",
"Joe Ingles",
"Terry Rozier",
"Spencer Dinwiddie",
"Kentavious CaldwellPope",
"Caris LeVert",
"DeMarre Carroll",
"Rodney Hood",
"Yogi Ferrell",
"Markieff Morris",
"DeAaron Fox",
"Darren Collison",
"JJ Barea",
"Joe Harris",
"John Collins",
"Lance Stephenson",
"Wesley Matthews",
"Jamal Crawford",
"Kelly Olynyk",
"Jeff Green",
"Pau Gasol",
"Frank Kaminsky",
"Marcin Gortat",
"Dwyane Wade",
"James Johnson",
"Denzel Valentine",
"John Wall",
"Justin Holiday",
"Nikola Mirotic",
"Tyler Johnson",
"John Henson",
"Myles Turner",
"Patty Mills",
"Kent Bazemore",
"Mario Hezonja",
"Draymond Green",
"Avery Bradley",
"Wayne Ellington",
"Mike Scott",
"Michael KiddGilchrist",
"Ersan Ilyasova",
"Reggie Jackson",
"Jae Crowder",
"Rudy Gobert",
"DAngelo Russell",
"Marcus Morris",
"Dejounte Murray",
"Dwight Powell",
"Wilson Chandler",
"Kris Dunn",
"Evan Turner",
"Malcolm Brogdon",
"Jakob Poeltl",
"Dewayne Dedmon",
"Trey Lyles",
"Nicolas Batum",
"Rudy Gay",
"Reggie Bullock",
"Pascal Siakam",
"Trevor Ariza",
"Cory Joseph",
"Marvin Williams",
"JR Smith",
"Doug McDermott",
"Jerami Grant",
"Troy Daniels",
"George Hill",
"Kyle Anderson",
"Jarrett Allen",
"DJ Augustin",
"Fred VanVleet",
"Larry Nance Jr",
"AlFarouq Aminu",
"Alex Len",
"Greg Monroe",
"Raymond Felton",
"CJ Miles",
"Tyler Ulis",
"Stanley Johnson",
"Danny Green",
"Anthony Tolliver",
"Rajon Rondo",
"Jerian Grant",
"David West",
"Kyle Korver",
"Kyle OQuinn",
"Aron Baynes",
"JaMychal Green",
"Marquese Chriss",
"Jarell Martin",
"Mason Plumlee",
"Shabazz Napier",
"Darius Miller",
"Manu Ginobili",
"Bryn Forbes",
"Ryan Anderson",
"Ian Clark",
"Kosta Koufos",
"Luke Kennard",
"Jarrett Jack",
"Skal Labissiere",
"TJ McConnell",
"Nick Young",
"Emmanuel Mudiay",
"Justise Winslow",
"Dragan Bender",
"David Nwaba",
"Gorgui Dieng",
"Delon Wright",
"Bismack Biyombo",
"Garrett Temple",
"Tomas Satoransky",
"Lonzo Ball",
"Andrew Harrison",
"Paul Millsap",
"Trey Burke",
"Marcus Smart",
"Tony Snell",
"Frank Ntilikina",
"Tyler Zeller",
"Trevor Booker",
"Devin Harris",
"Josh Hart",
"James Ennis III",
"OG Anunoby",
"Alec Burks",
"Shelvin Mack",
"Justin Jackson",
"Pat Connaughton",
"Mario Chalmers",
"Bam Adebayo",
"Ed Davis",
"PJ Tucker",
"Isaiah Taylor",
"Dion Waiters",
"Tony Parker",
"Nemanja Bjelica",
"Maxi Kleber",
"Luc Mbah a Moute",
"Shaun Livingston",
"Gerald Green",
"Wesley Johnson",
"Deyonta Davis",
"Dante Cunningham",
"Jodie Meeks",
"Davis Bertans",
"Jabari Parker",
"Jonas Jerebko",
"Tyus Jones",
"Malik Monk",
"Maurice Harkless",
"Ben McLemore",
"Norman Powell",
"Joe Johnson",
"Amir Johnson",
"Milos Teodosic",
"Mike Muscala",
"Andre Iguodala",
"Zaza Pachulia",
"Marreese Speights",
"Nene",
"Tristan Thompson",
"Frank Mason",
"Richaun Holmes",
"Tyler Dorsey",
"Ian Mahinmi",
"Thon Maker",
"Mike James",
"Cristiano Felicio",
"Quincy Acy",
"Langston Galloway",
"Sam Dekker",
"Daniel Theis",
"Corey Brewer",
"Thabo Sefolosha",
"Tyson Chandler",
"Quinn Cook",
"Royce ONeale",
"JaVale McGee",
"Isaiah Thomas",
"Sean Kilpatrick",
"Jordan Bell",
"Malcolm Delaney",
"Wayne Selden",
"Zach LaVine",
"Channing Frye",
"Danilo Gallinari",
"Jerryd Bayless",
"Tyrone Wallace",
"Omri Casspi",
"Al Jefferson",
"Vince Carter",
"Alex Abrines",
"Zach Collins",
"Kevon Looney",
"Miles Plumlee",
"Lance Thomas",
"Timothe LuwawuCabarrot",
"Patrick Patterson",
"Jameer Nelson",
"Chandler Parsons",
"Patrick McCaw",
"Cheick Diallo",
"Luke Babbitt",
"Jose Calderon",
"Willy Hernangomez",
"Noah Vonleh",
"Salah Mejri",
"Cedi Osman",
"Justin Anderson",
"Treveon Graham",
"Joffrey Lauvergne",
"Ivan Rabb",
"Tyler Ennis",
"Andre Roberson",
"Sindarius Thornwell",
"Derrick Rose",
"Wes Iwundu",
"Shabazz Muhammad",
"CJ Williams",
"Paul Zipser",
"Kenneth Faried",
"Cody Zeller",
"Terrence Ross",
"Joe Young",
"Dwayne Bacon",
"Willie Reed",
"Shane Larkin",
"Boban Marjanovic",
"Cameron Payne",
"Michael CarterWilliams",
"Tim Frazier",
"Terrance Ferguson",
"Kobi Simmons",
"Malik Beasley",
"Jawun Evans",
"Jahlil Okafor",
"Damyean Dotson",
"Sterling Brown",
"Raul Neto",
"Dwight Buycks",
"Tarik Black",
"Tyler Cavanaugh",
"Khem Birch",
"Mike Conley",
"Johnny OBryant III",
"Semi Ojeleye",
"Arron Afflalo",
"Jason Terry",
"Brandan Wright",
"TJ Leaf",
"Danuel House",
"Matthew Dellavedova",
"Ekpe Udoh",
"Torrey Craig",
"Henry Ellenson",
"Damion Lee",
"Eric Moreland",
"Nik Stauskas",
"Ivica Zubac",
"MarShon Brooks",
"DeAndre Bembry",
"Timofey Mozgov",
"Josh Huestis",
"Brandon Paul",
"Lucas Nogueira",
"Patrick Beverley",
"Nerlens Noel",
"Meyers Leonard",
"Isaiah Canaan",
"Abdel Nader",
"Markelle Fultz",
"Shaquille Harrison",
"Jonathan Isaac",
"Kawhi Leonard",
"Dorian FinneySmith",
"Alex Caruso",
"Tony Allen",
"JaKarr Sampson",
"Jared Dudley",
"Luke Kornet",
"Johnathan Motley",
"Myke Henry",
"Dante Exum",
"Jason Smith",
"Kyle Collinsworth",
"Troy Williams",
"Antonio Blakeney",
"DeAndre Liggins",
"Isaiah Whitehead",
"Ante Zizic",
"Ramon Sessions",
"Isaiah Hicks",
"Jamel Artis",
"Glenn Robinson III",
"Rodney Purvis",
"Jamil Wilson",
"Jordan Mickey",
"Malachi Richardson",
"Gary Payton II",
"Jalen Jones",
"Aaron Brooks",
"Emeka Okafor",
"Alec Peters",
"Mirza Teletovic",
"Guerschon Yabusele",
"Rodney McGruder",
"Caleb Swanigan",
"Iman Shumpert",
"Juan Hernangomez",
"Derrick Jones Jr",
"Kay Felder",
"Brandon Jennings",
"Darrell Arthur",
"Rashad Vaughn",
"Marcus GeorgesHunt",
"Aaron Harrison",
"Travis Wear",
"Georgios Papagiannis",
"Ron Baker",
"Chris McCullough",
"Dakari Johnson",
"Briante Weber",
"Ryan Arcidiacono",
"Brice Johnson",
"Jon Leuer",
"Jabari Bird",
"Davon Reed",
"Jake Layman",
"Andrew Bogut",
"Wade Baldwin IV",
"Jonathan Gibson",
"Quincy Pondexter",
"Bobby Brown",
"Lorenzo Brown",
"Andrew White III",
"Josh Magette",
"Derrick White",
"Richard Jefferson",
"John Holland",
"Milton Doyle",
"Josh Gray",
"Solomon Hill",
"Damian Jones",
"Damien Wilkins",
"Alex Poythress",
"Omari Johnson",
"Jack Cooley",
"Omer Asik",
"Nigel Hayes",
"DJ Wilson",
"Antonius Cleveland",
"Furkan Korkmaz",
"Alfonzo McKinnie",
"Thomas Bryant",
"Nick Collison",
"Andre Ingram",
"Adreian Payne",
"Okaro White",
"Alan Williams",
"Kyle Singler",
"Jordan Crawford",
"Larry Drew II",
"Demetrius Jackson",
"Bruno Caboclo",
"Derrick Walton Jr",
"RJ Hunter",
"Zhou Qi",
"Jeff Withey",
"Gian Clavell",
"Julyan Stone",
"Andrew White",
"James Webb III",
"Kadeem Allen",
"James Young",
"Jeremy Lin",
"Daniel Hamilton",
"Jaylen Morris",
"Darrun Hilliard",
"Joakim Noah",
"Walter Lemon Jr",
"Ike Anigbogu",
"Monte Morris",
"Cole Aldrich",
"Xavier RathanMayes",
"Mangok Mathiang",
"Malcolm Miller",
"Marcus Paige",
"Marquis Teague",
"Aaron Jackson",
"Joel Bolomboy",
"Vincent Hunter",
"Tony Bradley",
"Juancho Hernangomez",
"Udonis Haslem"]


